version: '3.6'

services:
  cloudbeaver-ce:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: cloudbeaver-ce-development
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    ports:
      - 8978:8978
    volumes:
      - ./data/cloudbeaver-ce:/opt/cloudbeaver/workspace
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8978/"]
      interval: 30s
      timeout: 10s
      retries: 3
